### PR TITLE
"Error! Bad return status for module build on kernel: 5.15.32-v8+"

### PR DESCRIPTION
**Pull request by b08x**
[Here](https://forum.seeedstudio.com/t/respeaker-4mic-array-install-on-raspberryos-with-5-15-kernel/264254/3) explains the what and why

Also works using 5.15.32-v7+ on rpi3

### CODE REVIEW

**Comment by HinTak** [comment]
Use https://github.com/HinTak/seeed-voicecard . Fixed ages ago.

**Comment by b08x** [comment]
Is there a reason you don't merge with this one? Other than this issue I've only had adjust problems with the bash install script, as it's limited in capacity when it comes to accounting for paths and different naming schemes.

**Comment by HinTak** [comment]
You'll have to ask Seeed Studio staff (I don't work for them). My fork has been around for a few years and they are aware of it. It is, as it says at the top, an on-going effort. I subscribe to the original Linus / git usage - it allows people to disagree and keep forks semi-permanently, with occasional cherry-pick's. This is an actual git technology where selected commits are incorporated, not whole-sale merge.

**Comment by HinTak** [comment]
FWIW, to be honest, I find it mildly offensive when people asked "why don't you do a pull/merge?". I don't work for seeed studio. Just another customer. It is the same category of questions you ask people: you donate x to this cause, why don't you donate more. WTF.

**Comment by yezzerfv** [comment]
> FWIW, to be honest, I find it mildly offensive when people asked "why don't you do a pull/merge?". I don't work for seeed studio. Just another customer. It is the same category of questions you ask people: you donate x to this cause, why don't you donate more. WTF.

I expect people may not realise this. Your work is much appreciated btw and I donated a while back :)

**Comment by HinTak** [comment]
@yezzerfv thanks, I appreciate that. In fact my Pi has been out of action for some months now (unrelated), but I am on x86_64 linux desktop all the time. So it is quite easy to do small things like updating the driver code for more recent kernels. The x86 desktop kernel updates are like a few a month (I don't reboot often, once a month or so onto a different kernel), and mostly you just see if the driver code still builds; if not, look up why. It is not too hard if each breakage is small.

It is a lot harder if you wait for the rasperrypi people to do their large kernel update jumps once every 6-12 months. Then you find it broken in multiple (complicated) ways.

**Comment by b08x** [comment]
> My fork has been around for a few years and they are aware of it.

Yeah, sorry I wasn't aware of _your_ particular thing. I wasn't aware that your repo existed until two days ago...what does that mean to you? 

I find it frustrating having to consult multiple sources, trying to figure out if someone else's work is going to break my system. It is sort of tedious and I try to avoid having to do that as much as possible.  Obviously you and I disagree on how git should be utilized, which is fine as your point is just as valid.

>  It is the same category of questions you ask people: you donate x to this cause, why don't you donate more. WTF.

WTF indeed. I wasn't asking you to put in more effort. I was asking why the effort wasn't made to work with the original source. Which, you answered by telling me you don't work for them so I should ask them. I don't think I want to make myself seem misguided by asking a member of Seeed's development team why _you never contacted them_. Think about that. 

You seem to think (and yes I'm assuming here, based on your response) that I don't understand the effort you've put into this. I do apologize that my words affected you in a negative way. I'm also sorry you felt the need to use language that sort of offends me, even if that wasn't your intention. I'm sure you don't care, but this is one reason why I won't use your fork. I simply asked you a question about a system a lot of us use and you replied with offense. This smacks of arrogance which I'm sure isn't how you want to represent yourself.

**Comment by HinTak** [comment]
If you had bothered to look at all, your problem was filed and marked as resolved perhaps a dozen times, here. You are about the 10th person who asked that same question. I am in the same situation, since a few years ago, as you: lack of maintaince by seeed studio staff of the small piece of hardware I bought a few years ago. WTF.

**Comment by HinTak** [comment]
#326 #324 #323 for example.

**Comment by b08x** [comment]
> If you had bothered to look at all, 

Your opinion is not welcome. It's irrelevant, useless and above all pathetic. Leave this discussion.

**Comment by b08x** [comment]
> #326 #324 #323 for example.

Oh great. More useless information I didin't ask for. Thank you so much.

**Pull request closed without merging**
