### PR TITLE
Suppress fallthrough warning

### PR DESCRIPTION
**Pull request by HinTak**

### CODE REVIEW

**Comment by HinTak** [comment]
? That's in the kernel for a while... I should check when it was introduced...

**Comment by HinTak** [comment]
Without the last one commit (or use `__attribute__((__fallthrough__))` instead of `fallthrough` - should work, but not as neat as what the kernel header recommends.

**Comment by HinTak** [comment]
@KillingJacky - apologies - didn't notice that section was new to v5.4 (the file itself is not, and auto-included by others) . Added compatibility code - see changelog.

**Comment by KillingJacky** [comment]
@HinTak It's OK. Now the code can be compiled well, thanks for the PULL.

**Comment by HinTak** [comment]
@KillingJacky you'd notice the two fallthrough warning messages are gone too. I looked at the actual surrounding code, and assumed that the fallthough (i.e. continue on to the next label's section) is intentional.

**Pull request merged**
