### PR TITLE
preserve user asound.conf 

### PR DESCRIPTION
**Pull request by mtrey**
if the user changes the content of `/etc/asound.conf` it is currently overwritten at each reboot.

the proposed change allow the user's settings to be preserved across reboot while still allowing the configuration to be done properly when the user first set up his device.

### CODE REVIEW

**Comment by Pillar1989** [comment]
@mtrey  If one people have 2mic and 4mic hat，your PR maybe not work .

**Comment by kali** [comment]
Hey @Pillar1989, would you mind elaborating a bit on this use-case ? Are you considering a case where a user would switch from one hat to the other and back on a regular basis ? This sounds like a "developer mode" more than a production or semi-production mode. An end-user would probably choose a hat and stick to it most of the time...

Our issue with the current state of affairs is that the default asound.conf does not work for us, we need to alter it. Could we find a middle ground where there is a way to disable the auto update ? One way could be to only replace un-altered configuration files and leave them alone if the user has changed them (maybe using a comment marker in the file ?)

**Comment by Pillar1989** [comment]
@kali  People didnt want frequently install seeed-voicecard.  thay just want to insert hats and use it. But You have a point too. I'll merge asound_2mic.conf ,asound_4mic.conf ,asound_6mic.conf to one asound.conf

**Comment by mtrey** [comment]
@Pillar1989 , I mostly use your devices with pulsaudio but for this we do not want the `/etc/asound.conf` to be recreated as it clash with pulseaudio. 

@kali proposal to have a configuration flag so only the `dto` is applied  sounds perfect to me it would address both use cases :

- User do have a customized asound.conf
- User do use pulseaudio

**Comment by Pillar1989** [comment]
@mtrey  That's a Beta version asound.conf  which merged 2-mic,4-mic,6-mic.   seeed-voicecard service will adjust the default playback and capture card on boot time. If the card hw number is wrong ,service will also modify it.

```
# The IPC key of dmix or dsnoop plugin must be unique
# If 555555 or 666666 is used by other processes, use another one

pcm.!default {
    type asym
    playback.pcm "2mic_p"
    capture.pcm "2mic_c"
}

#2Mic Hat settings
pcm.2mic_p {
    type plug
    slave.pcm "dmixed"
}
pcm.dmixed {
    type dmix
    slave.pcm "hw:0,0"
    ipc_key 111111 
}
pcm.2mic_c {
    type plug
    slave.pcm "array"
}
pcm.array {
    type dsnoop
    slave {
        pcm "hw:0,0"
        channels 2
    }
    ipc_key 222222
}

#4Mic Hat settings
pcm.4mic_c {
    type plug
    slave.pcm "4micshare"
}

pcm.4micshare {
    type dsnoop
    ac108-slavepcm "hw:1,0"
    ipc_key 333333
}

pcm.4mic_p {
    type plug
    slave.pcm "hw:0,0"
}

#6Mic Hat settings
pcm.6mic_p {
	type plug
	slave {
		pcm {
			type dmix
			ipc_key 1048576
				slave {
				pcm		"hw:1,0"
				format		S32_LE
				# rate		16000
				channels	8
			}
			bindings {
				# map 2 channels input to
				# first 2 channels of 8 output
				0	0
				1	1
				0	2
				1	3
				0	4
				1	5
				0	6
				1	7
			}
		}
		channels	2
	}
}

pcm.6mic_c {
    type plug
    slave.pcm "6micshare"
}

pcm.6micshare {
    type dsnoop
    slave.pcm "hw:1,0"
    ipc_key 444444
}

```

**Comment by Pillar1989** [comment]
@mtrey Sorry, we spent a lot of time dealing with this PR.We consulted a lot of users and finally chose a way that everyone liked. 
The user's asound.conf would be saved. If the user broke it, the user could also restore to the original state through git command.You can use the code for the dev branch to get these updates, and I'll merge the dev branch with the master branch shortly.

**Pull request closed without merging**
