### PR TITLE
Don't force kernel downgrade

### PR DESCRIPTION
**Pull request by HinTak**
Revert "Fix: try to use a specific version kernel & headers"

This reverts commit ae32476755bf458cdd8883d6975082a244eb9d87.

Conflicts:
	install.sh

### CODE REVIEW

**Comment by KillingJacky** [comment]
@HinTak Thanks for the PR, instead of totally removing the compatible approach with working kernels, I created another PR which keeps the option for users to choose the older working kernel, in case of the raspbian kernel breaks the driver in the future again. Thank you very much for your works on pushing the fix of upstream.

**Comment by HinTak** [comment]
I think https://github.com/respeaker/seeed-voicecard/issues/238 is another manifestation of this bug : the raspian people simply don't keep too many old versions around. 

For example, I just use my raspbian box, and the only available option is upgrade to 1.20200723-1, which is 5.4.51 : 

```
pi@raspberrypi:~ $ apt-cache policy raspberrypi-kernel
raspberrypi-kernel:
  Installed: 1.20200512-2
  Candidate: 1.20200723-1
  Version table:
     1.20200723-1 500
        500 http://archive.raspberrypi.org/debian buster/main armhf Packages
 *** 1.20200512-2 100
        100 /var/lib/dpkg/status
```

**Comment by turmary** [comment]
@HinTak 
The FORCE_KERNEL version kernel, could be found always in
https://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/

So I think give a command line argument to the end user to using old kernel is a good thing.

Thanks you for your PR, close now.

**Comment by HinTak** [comment]
That's a single archive web site, and not reachable nor used by `apt`. While you can even go further as to just copy them into Seeed Studio location, many users do not want to run old software, or for other reasons, cannot. I personally just refuse to be restricted to old / outdated versions.

**Pull request closed without merging**
